### ISSUE TITLE
Thank you for the test app!

### ISSUE THREAD

**Issue by pajtai** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated-app-example#3]
Hi @andrehtissot thank you for your FCM plugin, and especially thank you for this test app.

I haven't been able to add the FCM plugin to an existing Cordova app because iOS is not firing the device ready event... but Android is working.

I did get this test app to work on iOS, so that gives me the confidence to spend the time to debug what's going on in my original app.

Thanks!

**Comment by andrehtissot** [comment]
Thank you, some issues are very hard to find.
Knowing that it helps people is the reason this was created and why the main plugin is evolving.
